# ---------------------------------------------------------------------------- #
#                |   █████╗ ██╗   ██╗██████╗  █████╗ ███████╗ |                #
#                |  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ |                #
#                |  ███████║██║   ██║██████╔╝███████║█████╗   |                #
#                |  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   |                #
#                |  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ |                #
#                |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ |                #
#                +--------------------------------------------+                #
#                                                                              #
#                         Distributed Systems Runtime                          #
# ---------------------------------------------------------------------------- #
# Copyright 2022 - 2024, the aurae contributors                                #
# SPDX-License-Identifier: Apache-2.0                                          #
# ---------------------------------------------------------------------------- #
#
name: "(002) make pki config auraed-test"
on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  packages: write
env:
  CARGO_TERM_COLOR: always
jobs:
  build-container:
    uses: ./.github/workflows/100-aurae-builder-image-docker-build-builder.yml
  build:
    name: Build (lint, compile, test)
    runs-on: ubuntu-latest
    needs: build-container
    timeout-minutes: 30
    container:
      image: ghcr.io/${{ github.repository }}/aurae-builder:builder-latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: 002-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            100-${{ runner.os }}-cargo-
      - name: Cargo Test [make pki config test]
        # This should remain the only command we execute as this matches the title of the file.
        # The goal is for this to be easy to find from the GitHub dashboard.
        # Instead of adding more commands here, consider another make target or a new YAML file
        # named with a good name.
        run: make pki config auraed-test
